# SPDX-License-Identifier: GPL-2.0
obj-y += stp_wmt_stub.o
ccflags-y += -I$(srctree)/drivers/misc/mediatek/connectivity/conninfra/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/connectivity/compat/include
ccflags-y += -include $(srctree)/drivers/misc/mediatek/connectivity/bt/shim/mtk_compat_types.h
